# Generated by Django 2.2.5 on 2022-05-11 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('receta', models.CharField(choices=[('Con receta', 'Con receta'), ('Venta libre', 'Venta libre')], max_length=1)),
                ('precio', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
                ('fechaalta', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.CharField(choices=[('Médico de familia', 'Médico de familia'), ('Digestivo', 'Digestivo'), ('Neurologo', 'Neurologo'), ('Dermatólogo', 'Dermatólogo'), ('Traumatólogo', 'Traumatólogo')], default='Médico de familia', max_length=25)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('edad', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasSeguros.Compra')),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasSeguros.Medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasSeguros.Paciente'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
                ('idMedico', models.ForeignKey(on_delete='cascade', to='consultasSeguros.Medico')),
                ('idPaciente', models.ForeignKey(on_delete='cascade', to='consultasSeguros.Paciente')),
            ],
        ),
    ]
