# Generated by Django 2.2.5 on 2022-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasSeguros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
