# Generated by Django 2.2.5 on 2022-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasSeguros', '0002_auto_20220512_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='receta',
            field=models.CharField(choices=[('s', 'Con receta'), ('v', 'Venta libre')], max_length=1),
        ),
    ]
