# Generated by Django 2.2.5 on 2022-05-31 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasSeguros', '0003_auto_20220530_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
