# Generated by Django 2.2.5 on 2022-06-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasSeguros', '0004_auto_20220601_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.CharField(max_length=30),
        ),
    ]
